### ISSUE TITLE
Question: a way to wait for page "sections" before route transition?

### ISSUE THREAD

**Issue by lunelson** [graysonhicks/gatsby-plugin-loadable-components-ssr#37] opened 2021-09-15 15:36 UTC
I've been leaning so far to the conclusion that this can only be done with upcoming Suspense, concurrent-mode etc. in React 18, but is there any way that I could make the client-side router wait for loadable-component sections of the incoming page before doing the route transition?

**Comment by graysonhicks** [comment] 2021-11-15 04:36
Hm, there shouldn't be any client side 'waiting' for sections using this plugin because they should be SSR'd.  Can you explain more of the expected behavior?

**Comment by lunelson** [comment] 2021-11-15 07:40
Hi, 👋🏻  yes they are SSR'd on a cold load, but not on Router transitions, e.g. if I do a full page-load on "Page A", everything comes in one piece, but if I then go to "Page B", and this page contains some components which were not already on page A, the Router doesn't "know" about the loadable components on the page, so the transition happens immediately and then the different loadable parts of the page will flash in as they load

**Comment by graysonhicks** [comment] 2021-12-11 04:58
Closing this for now, feel free to reopen with a reproduction, thanks!

**Closed by graysonhicks** 2021-12-11 04:58 UTC
