### ISSUE TITLE
Cannot find module '/.cache/page-ssr/loadable-stats-build-javascript.json'

### ISSUE THREAD

**Issue by Pearce-Ropion** [graysonhicks/gatsby-plugin-loadable-components-ssr#48] opened 2021-12-03 05:00 UTC
Hi,

I am experiencing an error on `gatsby develop` and `gatsby build`. Essentially the new location for `loadable-stats-build-javascript.json` in the latest version cannot be resolved during the SSR phase.

```
There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html  Cannot find module
'/.cache/page-ssr/loadable-stats-build-javascript.json'

  853 |         }]
  854 |       }]
> 855 |     });
      |      ^
  856 |   } else {
  857 |     children.push(main.icon);
  858 |   }
```

From my testing, `process.cwd()` resolves to `/` during the gatsby SSR phase. Therefore, the resulting json file path in `gatsby-ssr` is `/.cache/page-ssr/loadable-stats-build-javascript.json` (note the leading slash `/` and not `./`)

One option to fix this is to export only the relative path from `constant.js`
```javascript
export const LOADABLE_STATS_FILE_PATH = path.join(
  // process.cwd() >>  remove this
  GATSBY_CACHE_PATH,
  GATSBY_RENDER_VALIDATION_PREFIX_PATH,
  LOADABLE_STATS_FILE_NAME
)
```
and then in `gatsby-node`
```javascript
filename: path.join(process.cwd(), LOADABLE_STATS_FILE_PATH)
```

and in `gatsby-ssr`:
```javascript
statsFile: path.resolve(LOADABLE_STATS_FILE_PATH)
```

I am happy to submit a PR if needed.

**Comment by graysonhicks** [comment] 2021-12-11 04:50
Thanks for the issue and PR @Pearce-Ropion !  For posterity and clarity, what are the steps to reproduce this?  Does it happen on every build or randomly?  Is this OS dependent?  Thanks and I'll get this merged and released asap!

**Comment by Pearce-Ropion** [comment] 2021-12-11 05:05
I'm currently running on Debian 9, so it might be OS specific. I know Linux sometimes does weird stuff with paths. 

As for when this happens, it appears to happen on every build and development build on the latest version of gatsby. I had to look through a bunch of the files in the gatsby codebase while researching what was the problem and found a lot of places where they reference the /page-ssr directory like you do during gatsby-node API process. But I couldn't find anywhere where they try to access a file in /page-ssr during the gatsby-ssr API process. So maybe this is just how gatsby works during the SSR step. 

I was just testing this in my local repository, but if you'd like I could try to make a repro.

**Comment by graysonhicks** [comment] 2021-12-11 14:46
Yea, if you don't mind, that'd be great!  I just want to be careful on this pathing because there have been several fixes related to OS here and don't want a regression.  Thanks!

**Comment by yukulelix** [comment] 2021-12-14 11:29
This is happening on Gatsby Cloud for me too :)

**Comment by graysonhicks** [comment] 2021-12-16 16:41
Released 4.1.1 with a fix for this.  Thanks @Pearce-Ropion !

**Comment by reilnuud** [comment] 2021-12-17 19:33
@graysonhicks – it's back, reverting from 4.1.2 to to 4.1.1 fixes it--leading / strikes again:

[abe2da04408c505cbacf11beeca24fbd98a809ba]((https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/commit/abe2da04408c505cbacf11beeca24fbd98a809ba))

**Comment by graysonhicks** [comment] 2021-12-17 19:41
@pieh Any ideas why one breaks the other?

**Comment by reilnuud** [comment] 2021-12-17 19:46
My guess would be that the path needs to be resolved still--it's looking for .cache in the system root, not the project root.

**Comment by Pearce-Ropion** [comment] 2021-12-17 19:54
Yep, importing from any path that starts with / will import from the system root.

**Comment by graysonhicks** [comment] 2021-12-17 19:55
As long as you aren't using DSG, you can stay on 4.1.1

**Comment by Pearce-Ropion** [comment] 2021-12-17 19:56
I think you forgot the leading ./ in your import path to make it relative.

**Comment by graysonhicks** [comment] 2021-12-17 20:00
Can't tell if that / is important for the DSG aspect: https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/pull/50#discussion_r770928104

**Comment by bwlng** [comment] 2021-12-17 20:03
@graysonhicks I can test on our project if a beta release is tagged

**Comment by Leksat** [comment] 2021-12-21 14:36
Adding `.` before `/` does not help.
```
Module not found: Error: Can't resolve './.cache/page-ssr/loadable-stats-build-javascript.json' in
'/path-to-project/node_modules/gatsby-plugin-loadable-components-ssr'

```

But notice the path. It tries to find the file in the plugin dir, not in the project root.

**Comment by Leksat** [comment] 2022-01-06 09:55
Could we at least reopen this issue?

**Comment by graysonhicks** [comment] 2022-01-18 18:15
@pieh Any ideas on [this commit](https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/commit/abe2da04408c505cbacf11beeca24fbd98a809ba) causing this problem?  Ideally this should work with v4 + DSG.

**Comment by pieh** [comment] 2022-01-21 21:14
Path starting with `/` is intentional as that _should_ resolve to project root in Gatsby. And in test sites that I had as well as at least 1 user case it does work correctly.

To fix the problem I do need to be able to reproduce it - do any of you folks seeing this issue have (public) site I could pull and reproduce this on?

**Comment by samirergaibi** [comment] 2022-01-27 07:03
We've got the same issue when updating to `4.1.2`. I don't know if this helps but we've got a **mono repo** setup and from what I can tell it can't find the `loadable-stats-build-javascript.json` file since it's trying to find it in the plugin directory inside the `node_modules` folder instead of the projects folder where the `.cache` directory is as @Leksat pointed out.

**Comment by Bogdan1001** [comment] 2022-01-27 15:40
I got the same issue when I've deleted the .cache folder, I didn't update anything, I'm on Mac 13 m1.

 Can't run the project. Any fast workarounds?

**Comment by reilnuud** [comment] 2022-01-27 16:33
> I got the same issue when I've deleted the .cache folder, I didn't update anything, I'm on Mac 13 m1.
> 
>  Can't run the project. Any fast workarounds?

If you install 4.1.1, you should be able to avoid this error.

**Comment by Bogdan1001** [comment] 2022-01-27 16:44
@reilnuud that didn't help I've tried. I actually didn't change the version just after the cache was deleted by me it stopped to work not sure how it happened.

@graysonhicks I did some debugging. And I am sure that the 'loadable-stats-build-javascript.json' is created not at the right time(after it was requested by the module).

**What steps I've made?**
1. I tried to change the path at the module and that didn't help at all. After that, I did understand that the file does not exist.
2. I've copied 'loadable-stats-build-javascript.json' in another folder and then run 'gatsby develop' and just paste the 'loadable-stats-build-javascript.json' into .cache/page-ssr  and after that, all start working well even after the restart, and then once I cleared the cache all broke again. So I've repeated this manual injection and the project work again, and the issue does not appear with 'gatsby build'.

Please can you check the lifecycle and ensure that the 'loadable-stats-build-javascript.json' was created in the time as requested by the module? Let me know if I can help you debug it in my environment.

**Comment by graysonhicks** [comment] 2022-01-27 19:21
One thing that I think needs to happen is the plugin will essentially be ignored in develop because it's not necessary and is where I think this error occurs.

**Comment by pieh** [comment] 2022-01-30 10:17
I opened PR with essentially what @graysonhicks mentioned ("ignoring" develop) - https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/pull/51 (so plugin should be no-op for develop, but continue to add <script>/<style> tags to html in builds.

**Comment by graysonhicks** [comment] 2022-02-02 16:17
Okay, published the fix as a beta under `4.2.0-beta.0` if anyone would like to test.  Will publish later this week.

**Comment by cameronbraid** [comment] 2022-02-03 01:41
`4.2.0-beta.0` gets me passed that problem

**Comment by yangbooom** [comment] 2022-02-03 03:42
> Okay, published the fix as a beta under `4.2.0-beta.0` if anyone would like to test. Will publish later this week.

`4.2.0-beta.0` works great with gatsby develop too.

**Comment by laneparton** [comment] 2022-02-07 23:11
+1 for 4.2.0-beta.0

**Comment by graysonhicks** [comment] 2022-02-08 01:32
Thanks, feedback has been positive here and elsewhere.  Will release as `4.2.0` tomorrow.

**Comment by VernerKeel** [comment] 2022-02-15 05:19
+1 for 4.2.0-beta.0

**Closed** 2022-02-15 21:38 UTC

**Comment by graysonhicks** [comment] 2022-02-15 21:40
`4.2.0` just released.  Thanks all!

**Comment by graysonhicks** [comment] 2022-02-28 16:42
@Nikhil-Ladha Can you please open a new issue with a minimal reproduction?
