### ISSUE TITLE
WebpackError: Cannot find module 'public/loadable-stats-build-javascript.json'

### ISSUE THREAD

**Issue by dizip** [graysonhicks/gatsby-plugin-loadable-components-ssr#17] opened 2021-05-12 14:05 UTC
Hi everyone, 
I've changed the version of the plugin to 'next' and currently using Gatsby in 3.4 version.
Using Ubuntu everything works Ok, but on MacOS I am getting the following errors:

```
import setPrototypeOf from "./setPrototypeOf.js";

export default function _inherits(subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function");
  }

  WebpackError: Cannot find module 'public/loadable-stats-build-javascript.json'
```

Is there any chance you can advise me what I can do to fix that?

**Comment by hk86** [comment] 2021-05-14 07:32
Hi there, same error here. I use version `@next` due to gatsby V3.

**Comment by joelvarty** [comment] 2021-05-17 12:49
Same behaviour here.

**Comment by kszot-ref** [comment] 2021-05-18 10:01
Same issue here, but it only happens during a Cloud (incremental) build on Gatsby Cloud.

**Comment by graysonhicks** [comment] 2021-05-18 17:51
I just published an update on `next` adding the `writeToDisk` flag back.  This, plus another change, accidentally didn't make it in to that first beta.  Testing it now.

**Comment by joelvarty** [comment] 2021-05-18 17:54
> I just published an update on `next` adding the `writeToDisk` flag back. This, plus another change, accidentally didn't make it in to that first beta. Testing it now.

Fingers crossed!  Glad to see this package being maintained - thank you for all that you do!

**Comment by graysonhicks** [comment] 2021-05-18 19:41
Thanks @joelvarty !  I am also working on moving the test repo to Gatsby Cloud to be able to test builds in that pipeline as well as deployed behavior.

**Comment by graysonhicks** [comment] 2021-05-18 19:47
[Here is the demo site](https://loadabletestmain.gatsbyjs.io/) with the latest `next` version.  Cloud builds correctly, including subsequent builds and SSR is also happening correctly.  I was never able to replicate this problem myself, so I can't verify if it is resolved or not.

**Comment by afladmark** [comment] 2021-05-18 20:28
I definitely had that issue in testing, so I'll try out the `next` version locally with and without dev ssr, on a local build and on Gatsby Cloud and let you know. Thank for picking this up!

**Comment by joelvarty** [comment] 2021-05-18 20:49
My error has been resolved!

**Comment by afladmark** [comment] 2021-05-18 23:35
OK. I've tested everything with `2.2.1-beta.0` which is what was installed when I added `next` on Gatsby 3.2.

- **develop w/DEV SSR:** seems to work as expected though none of the page body content is present in the source. The `loadable-stats-build-javascript.json` file is in `public` as expected and this matches our previously working local code. So probably OK? I'm not entirely clear on whether I should expect it here.
- **develop with DEV SSR disabled:** Throws `WebpackError: Cannot find module '/Users/andrew/Repositories/gatsby_site/public/loadable-stats-build-javascript.json'`. The file is not present in the `public` folder, nor anywhere else.
- **both a local build and a gatsby cloud build:** Build succeeds without error but when examining the output HTML there is no SSR content. Just the Gatsby `<script>` tags and no body content whatsoever.

**Comment by graysonhicks** [comment] 2021-05-19 11:13
Thanks for the feedback @afladmark .  Do you have a reproduction?  Not seeing that behavior in my test repo.

**Comment by graysonhicks** [comment] 2021-05-19 11:19
@afladmark Scratch that, my build is successful with `2.2.1-beta.0`, but I see the error with `develop`.

**Comment by graysonhicks** [comment] 2021-05-19 11:27
Okay, `2.2.1-beta.2` (or `next` as of now) seems to resolve the issue for `develop`.  I am noticing that SSR does not work for DEV_SSR, but the build does.  I think I'd prefer seeing it working on a build that during the DEV_SSR, but there may be a fix for that long term.

cc: @afladmark

**Comment by chrisvince** [comment] 2021-05-19 12:48
`2.2.1-beta.2` works for me with `develop`! Thanks @graysonhicks!

**Comment by dizip** [comment] 2021-05-19 14:02
Also works for me, thanks for maintaining this package, it's very useful ;)

**Comment by afladmark** [comment] 2021-05-19 15:24
Confirmed develop with and without SSR now work as expected. 

I blew away `node_modules` and did a `gatsby clean` (and forced a build cache clear on Gatsby Cloud). I retested the build locally and on Gatsby Cloud and I seem to be getting the expected SSR content as well now. Not sure why it wasn't present before, but assume something was cached somewhere.

Interestingly, I seem to be getting the SSR content in DEV_SSR mode as well now which was definitely not the case yesterday either. <confused but happy!>

All seems good now. Thanks so much for your work on this!

**Comment by graysonhicks** [comment] 2021-05-19 19:20
Okay good news!  Thanks everyone.  I am closing this issue.  I think we are close to getting these updates out in a new major release.  There is one other bug I am working on and then it will be ready.

**Comment by Leksat** [comment] 2021-08-18 13:24
We get this error in Gatsby Cloud _randomly_.

Using the latest versions of all dependencies:
```
$ yarn list --pattern=loadable
├─ @loadable/babel-plugin@5.13.2
├─ @loadable/component@5.15.0
├─ @loadable/server@5.15.0
├─ @loadable/webpack-plugin@5.15.0
├─ @types/loadable__component@5.13.4
└─ gatsby-plugin-loadable-components-ssr@3.2.0
```

The error from Gatsby Cloud:
```
Building static HTML failed
WebpackError: Cannot find module '/usr/src/app/www/apps/website/public/loadable-stats-build-javascript.json'
```

Unfortunately, we could not find a way to reproduce the error locally. But here is what I have found after some research:
- Webpack config is adjusted only for three stages https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/blob/94736d30c534aea39c7a1d0fd7426c4e535c00b3/src/gatsby-node.js#L14-L19
- According to [Gatsby docs](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#onCreateWebpackConfig), the only stage left is `build-html`.
- This is the stage which fails in Gatsby Cloud.

So I thought maybe the `if` condition should be removed and the Webpack config should be set for all stages?

**Comment by graysonhicks** [comment] 2021-08-18 20:32
Thanks @Leksat that's interesting.  Yes, I have still seen this message show up, I think only on incremental builds.  @KyleAMathews What do you think?  Should the setWebpackConfig just run on every stage?

**Comment by KyleAMathews** [comment] 2021-08-18 20:54
Oh... I think this is the problem — https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/blob/94736d30c534aea39c7a1d0fd7426c4e535c00b3/src/gatsby-node.js#L34-L41

As an optimization, Gatsby Cloud reuses the previously created SSR bundle on incremental builds to SSR changed pages. But because we delete the JSON file, SSRing would fail.

I think if we just wrote the stats file to the .cache folder and didn't delete it we'd solve this issue. We shouldn't deploy this file but it's also arbitrary where we put it so let's just put it in `.cache`.

**Comment by Leksat** [comment] 2021-08-19 09:48
Here is a PR: https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/pull/32

**Comment by Leksat** [comment] 2021-08-19 09:50
When I tested locally, I also noticed that the npm package contains `constants.js` file which seems to be a leftover from the previous versions.

**Comment by graysonhicks** [comment] 2021-08-19 15:15
Merged #32 after testing locally and on Gatsby Cloud.  Seems to be a random and hard to reproduce error, but hopefully resolved.  Thanks @Leksat !

**Comment by jcpof** [comment] 2021-08-23 18:04
this is still an issue for me using teamcity build agents using windows. since we use a clean build directory the .cache folder does not exist at build time

**Comment by graysonhicks** [comment] 2021-08-24 00:37
@jcpof Can you elaborate?  Gatsby creates the `.cache` folder on every build.

**Comment by jcpof** [comment] 2021-08-24 00:40
> @jcpof Can you elaborate? Gatsby creates the `.cache` folder on every build.

im using teamcity for my builds, and we create a new directory for every build so the .cache folder wont be present.

i get this error `WebpackError: Cannot find module 'E:\BuildAgent\work\***folder\.cache\loadable-stats-build-javascript.json'`

**Comment by KyleAMathews** [comment] 2021-08-24 01:47
@graysonhicks if you use fs-extra `outputFile`, it'll ensure the directory is there.

**Comment by graysonhicks** [comment] 2021-08-24 03:06
@KyleAMathews Hm, okay.  But the the file is only [created](https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/blob/master/src/gatsby-node.js#L21) by the `LoadablePlugin` via `filename`.   Just create it via `outputFile` first?

**Comment by KyleAMathews** [comment] 2021-08-24 03:20
hm yeah — thinking about this more — @jcpof not sure how this isn't working. You run `gatsby build` in a new directory? When Gatsby starts up, pretty much the first thing it does to create the `.cache` directory if it doesn't exist.

**Comment by Leksat** [comment] 2021-08-24 15:09
Just wanted to confirm that the fix works for us on Gatsby Cloud. Thank you for help!

**Comment by lacsinagramar** [comment] 2021-08-25 14:11
I'm experiencing the same this issue on `gatsby develop`.

When I add this to my `gatsby-config.js`:

```javascript
{
      resolve: `gatsby-plugin-loadable-components-ssr`,
      options: {
        // Whether replaceHydrateFunction should call ReactDOM.hydrate or ReactDOM.render
        // Defaults to ReactDOM.render on develop and ReactDOM.hydrate on build
        useHydrate: true
      }
 },
```

My app won't build, and I get this error:
![image](https://user-images.githubusercontent.com/29629828/130806357-9b865396-00c1-40f6-930a-ff396ff232f0.png)

Please help me resolve this. Thank you

**Comment by rickyshowtime** [comment] 2021-09-01 09:12
I think this merge needs to be reviewed, my develop build now breaks on win32 system.
_loadable-stats-build-javascript.json_ is never written in .cache (for some strange reason it's actually written in root and /public folder) folder whereas for linux and macOS platforms it does (gatsby-plugin-loadable-components-ssr v3.3.0).

I made a downgrade to 3.2.0 and now develop builds (with and without SSR) are building fine.

**Closed** 2021-09-01 12:25 UTC
