### ISSUE TITLE
Cannot find module loadable-stats-build-javascript.json in development mode

### ISSUE THREAD

**Issue by artt** [graysonhicks/gatsby-plugin-loadable-components-ssr#18] opened 2021-05-18 13:42 UTC
> I did see a case of HMR not working in dev mode and have made a [repo here with steps to reproduce](https://github.com/graysonhicks/loadable-test) (it worked fine when I tried to reproduce).  If anyone wants to try it out.  If it is a confirmed issue, we can open a separate issue. 
>
> _Originally posted by @graysonhicks in https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/issues/12#issuecomment-837320313_

Confirm. The `build` works fine, but when I run `gatsby develop`, I get the following:

```
There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help
https://gatsby.dev/debug-html  Cannot find module
'[root]/public/loadable-stats-build-javascript.json'


  130 |             }
  131 |         }
> 132 |     }
      | ^
  133 |     catch (e_1_1) { e_1 = { error: e_1_1 }; }
  134 |     finally {
  135 |         try {


  WebpackError: Cannot find module '[root]/public/loadabl
  e-stats-build-javascript.json'
```

**Comment by leomelzer** [comment] 2021-05-18 15:25
Thanks for reporting, we are running into the same issue.

It seems like the webpack plugin lost `writeToDisk: true` here: https://github.com/graysonhicks/gatsby-plugin-loadable-components-ssr/pull/11/commits/00bc230e27ed05283c0d74a66e8867b15e20ea64 -- not sure what the original reason was to remove the option. 🤔 

Seems logical it can't find the stats file if it was not written to disk.

**Comment by graysonhicks** [comment] 2021-05-18 17:38
Thanks, this is a duplicate of #17

**Closed by graysonhicks** 2021-05-18 17:38 UTC
